### ISSUE TITLE
About the book Deploying to OpenShift

### ISSUE THREAD

**Issue by IssacPan** [jupyter-on-openshift/jupyterhub-quickstart#10]
I am reading your book Deploying to OpenShift. It's very helpful for learning OpenShift.
Do you mind I translate the book to Chinese Version?

**Comment by GrahamDumpleton** [comment]
No you cannot translate the book to Chinese. That isn't something I can personally give permission for as the content is owned by Red Hat. I will ask about whether we would allow translations, but we haven't done so in the past that I know of.

**Comment by IssacPan** [comment]
It's fine.If Red Hat needs more details,you can contract me with my personal email:issacpan@qq.com 




------------------ 原始邮件 ------------------
发件人: "Graham Dumpleton"<notifications@github.com>;
发送时间: 2018年4月26日(星期四) 凌晨5:15
收件人: "jupyter-on-openshift/jupyterhub-quickstart"<jupyterhub-quickstart@noreply.github.com>;
抄送: "Issac"<3672556@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jupyter-on-openshift/jupyterhub-quickstart] About the bookDeploying to OpenShift (#10)




No you cannot translate the book to Chinese. That isn't something I can personally give permission for as the content is owned by Red Hat. I will ask about whether we would allow translations, but we haven't done so in the past that I know of.
