### ISSUE TITLE
Deployment on Openshift \\"wait-for-database\\

### ISSUE THREAD

**Issue by oharach1** [jupyter-on-openshift/jupyterhub-quickstart#34]
Hi, I am trying to deploy jupyterhub on openshift using the templates and building jupyterhub image using as a reference this template

oc apply -f https://raw.githubusercontent.com/jupyter-on-openshift/jupyterhub-quickstart/master/build-configs/jupyterhub.json 

I am able to create the build config and the image stream, my problem is when I try to deploy the application, the pod for the dabase is running ok, but for some reason the pod for jupyterhub is not running and reviewing the Events section this show this error:

Error: container create failed: time="2020-09-23T02:02:31Z" level=error msg="container_linux.go:349: starting container process caused \"exec: \\\"wait-for-database\\\": executable file not found in $PATH\"" container_linux.go:349: starting container process caused "exec: \"wait-for-database\": executable file not found in $PATH"

Could someone please help me understand if this is something related to permissions while building the image? or when I try to deploy the application?

Thanks in advanced.

**Comment by GrahamDumpleton** [comment]
This project is effectively no longer maintained. The closest equivalent project there is is the Open Data Hub project from Red Hat. Suggest you try it and if have issues ask Red Hat.

**Comment by oharach1** [comment]
Thank you for the reply, just curious regarding Open Data Hub Operator, in specific for Jupyterhub, this could be customizable for authentication and other settings such as spawners? 
Regards,
Ohara

**Comment by GrahamDumpleton** [comment]
For questions about Open Data Hub ask Red Hat. Your question makes no sense around spawners though as it is specifically configured to host JupyterHub in OpenShift, which means it can only use the Kubernetes spawner. It doesn't make sense to swap out the spawner.
